apiVersion: v1
kind: ReplicationController
metadata:
  name: testrc1
spec:
  replicas: 2
  template:
    metadata:
      labels:
        env: prod
    spec:
      containers:
      - name: apache
        image: httpd
        ports:
        - containerPort: 80
